import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
import 'package:url_launcher/url_launcher.dart';

class Privacy extends StatefulWidget {
  static const String id = 'privacy';
  const Privacy({Key? key}) : super(key: key);

  @override
  State<Privacy> createState() => _PrivacyState();
}

class _PrivacyState extends State<Privacy> {
  @override
  Widget build(BuildContext context) {
    return  Scaffold(

      backgroundColor: Colors.white,
      body:Padding(
        padding: const EdgeInsets.symmetric(horizontal:30.0,vertical: 10),
        child: SingleChildScrollView(
          child: HtmlWidget(

            """
            <!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title>
    </title>
    <style>
        body {
            font-family: SpaceGrotesk;
            font-size: 12pt
        }

        h4,
        p {
            margin: 0pt
        }

        li {
            margin-top: 0pt;
            margin-bottom: 0pt
        }

        h4 {
            margin-top: 5pt;
            margin-bottom: 5pt;
            page-break-inside: auto;
            page-break-after: auto;
            font-family: 'SpaceGrotesk';
            font-size: 12pt;
            font-weight: bold;
            font-style: normal;
            color: #000000
        }

        .NormalWeb {
            margin-top: 5pt;
            margin-bottom: 5pt;
            font-family: 'SpaceGrotesk';
            font-size: 12pt
        }

        .sc-1e12e6a1-4 {
            margin-top: 5pt;
            margin-bottom: 5pt;
            font-family: 'SpaceGrotesk';
            font-size: 12pt
        }

        span.Heading4Char {
            font-family: 'SpaceGrotesk';
            font-weight: bold
        }

        span.Hyperlink {
            text-decoration: underline;
            color: #0563c1
        }

        span.UnresolvedMention {
            color: #605e5c;
            background-color: #e1dfdd
        }
    </style>
</head>

<body>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">Welcome! Thanks for visiting Changecollect, a digital asset platform. Use of the words &ldquo;Changecollect,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo; refer to any or all Changecollect entities and their affiliates. This Privacy Policy explains what Personal Information (as defined below) we collect, why we collect it, how we use and disclose it, your choices, any rights you may have, and how you can contact us about our privacy practices. By continuing to use Changecollect, you agree to this Privacy Policy. This Privacy Policy does not apply to third-party websites, products, or services, even if we provide links to them or they link to us.</span><br><br><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">Your privacy matters to us so whether you are new to Changecollect or a long-time customer, please do take the time to get to know and familiarize yourself with our policies and practices. Feel free to print and keep a copy of this Privacy Policy, but please understand that we reserve the right to change any of our policies and practices at any time. But don&rsquo;t worry, you can always find the latest version of this Privacy Policy here on this page.</span><br><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">1. Personal Information We Collect</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">Overview</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">Personal information typically means information that identifies or is reasonably capable of identifying an individual, directly or indirectly, and information that relates to, describes, is reasonably capable of being associated with or could reasonably be linked to an identified or reasonably identifiable individual. For the purposes of this Privacy Policy, only the definition of personal information from the applicable law of your legal residence will apply to you and be deemed your &ldquo;Personal Information.&rdquo;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><br><br><em><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">A. Personal Information we collect from you</span></em></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may collect the following categories of Personal Information directly from you:</span></p>
    <ul style="margin:0pt; padding-left:0pt;">
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Identification Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as name, email, phone number, postal address, and/or government-issued identity documents;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Commercial Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as trading activity, order activity, deposits, withdrawals, account balances;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Financial Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as bank account information, routing number;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Correspondence,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as information that you provide to us in correspondence, including account opening and customer support;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Audio, Electronic, Visual, Thermal, Olfactory, or Similar Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as images and videos collected for identity verification, audio recordings left on answering machines;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Biometric Information</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">, such as scans of your face geometry extracted from identity documents;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Professional or Employment-related Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as job title, source of wealth; and</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Institutional Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as for institutional customers, we may collect additional information, including: institution&rsquo;s legal name, Employer Identification Number (&ldquo;EIN&rdquo;) or any comparable identification number issued by a government, and proof of legal existence (which may include articles of incorporation, certificate of formation, business license, trust instrument, or other comparable legal document).</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Sensitive Personal Information</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">, such as government-issued identification numbers (which may include Social Security Number or equivalent, driver&rsquo;s license number, passport number).</span></li>
    </ul>
    <p style="line-height:18pt; background-color:#ffffff;"><br><em><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">B. Personal Information we collect automatically</span></em></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may collect the following categories of Personal Information automatically through your use of our services:</span></p>
    <ul style="margin:0pt; padding-left:0pt;">
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Online Identifiers,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as IP address; domain name;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Device Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as hardware, operating system, browser, screen size; and</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Usage Data,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as system activity, internal and external information related to Changecollect pages that you visit, clickstream information</span></li>
    </ul>
    <p style="line-height:18pt; background-color:#ffffff;"><br><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">Our automatic collection of Personal Information may involve the use of Cookies, described in greater detail below.</span><br><br><em><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">C. Personal Information we collect from third parties</span></em></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may collect and/or verify the following categories of Personal Information about you from Third Parties:</span></p>
    <ul style="margin:0pt; padding-left:0pt;">
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Identification Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as name, email, phone number, postal address;&nbsp;</span><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;</span></strong></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Financial Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as bank account information, routing number;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Transaction Information,&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">such as public blockchain data (bitcoin, ether, and other Digital Assets are not truly anonymous.</span><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:12pt;">We, and any others who can match your public Digital Asset address to other Personal Information about you, may be able to identify you from a blockchain transaction because, in some circumstances, Personal Information published on a blockchain (such as your Digital Asset address and IP address) can be correlated with Personal Information that we and others may have. Furthermore, by using data analysis techniques on a given blockchain, it may be possible to identify other Personal Information about you;</span><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Credit and Fraud Information,</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;such as credit investigation, credit eligibility, identity or account verification, fraud detection, or as may otherwise be required by applicable law;</span><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Sensitive Personal Information</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">, such as government identification numbers (which may include Social Security Number or equivalent, driver&rsquo;s license number, passport number); and</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Additional Information,</span></strong><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;as permitted by law or required</span><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;</span><span style="font-family:'SpaceGrotesk'; font-size:12pt;">to comply with legal obligations, which may include criminal records or alleged criminal activity, or information about any person or corporation with whom you have had, currently have, or may have a financial relationship.</span><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;</span></li>
    </ul>
    <p style="line-height:18pt; background-color:#ffffff;"><br><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">Personal Information you provide during the registration process may be retained, even if your registration is left incomplete or abandoned.</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">2. How We Use Your Personal Information</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">The Personal Information we collect and the practices described above are done in an effort to provide you with the best experience possible, protect you from risks related to improper use and fraud, and help us maintain and improve Changecollect. We may use your Personal Information to:</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><br><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">A. Provide you with our services.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We use your Personal Information to provide you with our services pursuant to the terms of our User Agreement. For example, in order to facilitate fiat transfers into and out of your account, we need to know your financial information.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">B. Comply with legal and regulatory requirements.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We process your Personal Information as required by applicable laws and regulations. For example, we have identity verification requirements to fulfill our obligations under the anti-money laundering laws of numerous jurisdictions and, as such, we may use an image of an identity document that you provide to help us verify that you are the true owner of the identity document and that the document does not show signs of fraud.</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">C. Detect and prevent fraud.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We process your Personal Information to detect and prevent fraud on your account, which is especially important given the irreversible nature of cryptocurrency transactions.</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">D. Protect the security and integrity of our services.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We use your Personal Information to further our security-first mentality. Maintaining the security of your account and the Exchange requires us to process your Personal Information, including information about your device and your activity on the Exchange, and other relevant information.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">E. Provide you with customer support.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We process your Personal Information anytime that you reach out to our Customer Support team, such as when there are issues arising from your account.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">F. Optimize and enhance our services.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We use your Personal Information to understand how our products and Services are being used to help us improve our Services and develop new products.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">G. Market our products to you.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may contact you with information about our products and services that we believe may be of interest to you. You may use tools that we provide to opt out of marketing communications from us at any time.</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">H. With your consent.</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;We may use your Personal Information for additional purposes with</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;your consent.</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">I. Other business purposes.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may use your Personal Information for additional purposes in the operation of our business, that would be reasonably expected based on context, and as permitted by law or required</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;to comply with our legal obligations.</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">3. How We Share Your Personal Information</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We will not share your Personal Information with third parties, except as described below:</span><br><br><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">A. Service Providers.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may share your Personal Information with third-party service providers for business or commercial purposes. Your Personal Information may be shared so that they can provide us with services, including identity verification, fraud detection and prevention, credit verification, security threat detection, payment processing, customer support, data analytics, Information Technology, advertising, marketing, data processing, network infrastructure, storage, transaction monitoring, and tax reporting. We share your Personal Information with these service providers only so that they can provide us with services, and we prohibit our service providers from using or disclosing your Personal Information for any other purpose. Our third-party service providers are subject to strict confidentiality obligations.</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">B. Affiliates.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may share your Personal Information with our affiliates for the purposes outlined above, and as it is necessary to provide you with our Services.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">C. Legal Obligations.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may be required or in good faith and in our sole discretion believe it is necessary to share your Personal Information with law enforcement, government agencies, regulators or third parties to comply with legal or regulatory requirements, or to preserve our rights or to protect against fraud or other illegal activity.</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">D. Corporate Transactions.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may disclose Personal Information in the event of a proposed or consummated merger, acquisition, reorganization, asset sale, or similar corporate transaction, or in the event of a bankruptcy or dissolution.</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">E. Professional Advisors.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may share your Personal Information with our professional advisors, including legal, accounting, or other consulting services for purposes of audits or to comply with our legal obligations.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">F. Consent.&nbsp;</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may share or disclose your information with your consent.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">G. Other business purposes.</span></strong><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;We may share or disclose your Personal Information for other business purposes as permitted by law.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span><br><br><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">If we decide to modify the purposes for which your Personal Information is collected, used, or shared, or our practices relating to your Personal Information, we will amend this Privacy Policy as described below.</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">4. Cookies</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">When you access Changecollect, we may make use of the standard practice of placing tiny data files called cookies, flash cookies, pixel tags, or other tracking tools (herein, &ldquo;Cookies&rdquo;) on your computer or other devices used to visit Changecollect. We use Cookies to help us recognize you as a customer, collect information about your use of Changecollect to better customize our services and content for you, and collect information about your computer or other access devices to: (i) ensure compliance with our Bank Secrecy Act (&ldquo;BSA&rdquo;) and anti-money laundering (&ldquo;AML&rdquo;) program (&ldquo;BSA/AML Program&rdquo;) (ii) ensure that your account security has not been compromised by detecting irregular, suspicious, or potentially fraudulent account activities; (iii) assess and improve our services and advertising campaigns.</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><br><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may make use of third-party Cookies or analytics services, including but not limited to Google Analytics, Facebook, and MixPanel.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <ul style="margin:0pt; padding-left:0pt;">
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:12pt;">To learn more about Google Analytics and how to opt-out of making your activities available to Google Analytics, please visit&nbsp;</span><a href="https://marketingplatform.google.com/about/" target="_blank" style="text-decoration:none;"><u><span style="font-family:'SpaceGrotesk'; font-size:12pt; color:#0000ff;">https://marketingplatform.google.com/about/</span></u></a><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;or&nbsp;</span><a href="https://support.google.com/analytics/answer/181881?hl=en" target="_blank" style="text-decoration:none;"><u><span style="font-family:'SpaceGrotesk'; font-size:12pt; color:#0000ff;">https://support.google.com/analytics/answer/181881?hl=en</span></u></a><span style="font-family:'SpaceGrotesk'; font-size:12pt;">.</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:12pt;">To learn more about how Facebook uses your data please visit&nbsp;</span><a href="https://www.facebook.com/help/325807937506242/" target="_blank" style="text-decoration:none;"><u><span style="font-family:'SpaceGrotesk'; font-size:12pt; color:#0000ff;">https://www.facebook.com/help/325807937506242/</span></u></a><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;or log on to your Facebook account and access your settings. To understand more about Facebook advertising please see here&nbsp;</span><a href="https://www.facebook.com/about/ads" target="_blank" style="text-decoration:none;"><u><span style="font-family:'SpaceGrotesk'; font-size:12pt; color:#0000ff;">https://www.facebook.com/about/ads</span></u></a><span style="font-family:'SpaceGrotesk'; font-size:12pt;">.</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:12pt;">To learn more about MixPanel, please visit&nbsp;</span><a href="https://mixpanel.com/legal/privacy-policy/" target="_blank" style="text-decoration:none;"><u><span style="font-family:'SpaceGrotesk'; font-size:12pt; color:#0000ff;">https://mixpanel.com/legal/privacy-policy/</span></u></a><span style="font-family:'SpaceGrotesk'; font-size:12pt;">.</span><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;</span><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;</span></li>
        <li style="margin-left:42.6pt; line-height:18pt; padding-left:8.4pt; font-family:serif; font-size:10pt; color:#010304; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:12pt;">Third-party tracking technologies are not controlled by us, and statements regarding our practices do not apply to these third-parties or their use of information. We make no representations regarding the policies or practices of such third parties. You may be able to opt out of the practices of some of these third parties if they are members of the Network Advertising Initiative (&ldquo;NAI&rdquo;) by visiting http://www.networkadvertising.org/choices or if they participate in the Digital Advertising Alliance (&ldquo;DAA&rdquo;) by visiting http://www.aboutads.info/choices. We are not responsible for effectiveness of or compliance with any third-parties&rsquo; opt-out options.</span><br><span style="font-family:'SpaceGrotesk'; font-size:12pt;">&nbsp;</span></li>
    </ul>
    <p style="line-height:18pt; background-color:#ffffff;"><br><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">You also can learn more about cookies by visiting&nbsp;</span><a href="https://www.allaboutcookies.org/" target="_blank" style="text-decoration:none;"><u><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#0000ff;">https://www.allaboutcookies.org</span></u></a><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">, which includes additional useful information on cookies and how to block cookies on different types of browsers and mobile devices.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">5. Direct Marketing</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">Subject to applicable laws and regulations, we may from time to time send direct marketing materials promoting services, products, facilities, or activities to you using information collected from or about you. You may opt-out of such marketing communications at any time by unsubscribing. You may also opt-out of such communications by following the directions provided in any marketing communication. It is our policy to not provide your Personal Information to</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;third parties for their own direct marketing purposes without your consent. If you opt out of marketing communications, please note that we may still send you necessary information about transactions or our business relationship.</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">6. Children&rsquo;s Personal Information</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">Changecollect is not intended for children under the age of 18 and we do not knowingly collect Personal Information of children under the age of 18. If we learn that we have collected any Personal Information from a child under the age of 18, we will promptly delete it from our systems.</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">7. Information Security</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We take reasonable measures, including administrative, technical, and physical safeguards, to protect your Personal Information from loss, theft, or misuse, and from unauthorized access, disclosure, alteration, and destruction. Nevertheless, no security is foolproof, and the Internet is an insecure medium. We cannot guarantee absolute security, but we work hard to protect Changecollect and you from unauthorized access to or unauthorized alteration, disclosure, or destruction of Personal Information we collect and store. Measures we take may include encryption of the Changecollect website communications with SSL; required two-factor authentication for all sessions; periodic review of our Personal Information collection, storage, and processing practices; and restricted access to your Personal Information on a need-to-know basis for our employees, contractors and agents who are subject to strict contractual confidentiality obligations and may be disciplined or terminated if they fail to meet these obligations.</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">8. Retention</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We retain your Personal Information for as long as is reasonably necessary to provide services to you, for our legitimate business purposes, and to comply with our legal and regulatory obligations. If you close your account with us, we will continue to retain your Personal Information as necessary to comply with our legal and regulatory obligations, including for fraud monitoring, detection and prevention; and for our tax, accounting, and financial reporting obligations.&nbsp;</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">9. International Transfers</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">Changecollect is a global business. As a result, Personal Information may be stored and processed in any country where we have operations or where we engage service providers. We may transfer Personal Information that we maintain about you to recipients in countries other than the country in which the Personal Information was originally collected. Those other countries may have data protection or privacy rules that are different from those of your country. However, we will take measures to ensure that any such transfers comply with applicable data protection laws and that your Personal Information remains protected to the standards described in this Privacy Policy. In certain circumstances, courts, law enforcement agencies, regulatory agencies or security authorities in those other countries may be entitled to access your Personal Information.</span></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">10. Updates To this Privacy Policy</span></strong><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">&nbsp;</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">We may change this Privacy Policy from time to time to reflect changes to our privacy practices, enhance user experience, or comply with relevant laws. The date at the top of this Privacy Policy indicates when this Privacy Policy was last revised. Any changes are effective when we post the revised Privacy Policy. Your continued use of Changecollect after our posting of changes to this Privacy Policy means that you understand and agree to such changes.</span><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">&nbsp;</span></p>
    <p style="margin-top:18.75pt; margin-bottom:6pt; line-height:24pt; background-color:#ffffff;"><strong><span style="font-family:'SpaceGrotesk'; font-size:18pt; color:#010304;">11. Contact Us</span></strong></p>
    <p style="line-height:18pt; background-color:#ffffff;"><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">If you have questions or concerns regarding this policy or our processing of your Personal Information, please feel free to email us at:&nbsp;</span><a href="mailto:info@Changecollect.com" style="text-decoration:none;"><span class="Hyperlink" style="font-family:'SpaceGrotesk'; font-size:13.5pt;">info@Changecollect.com</span></a><span style="font-family:'SpaceGrotesk'; font-size:13.5pt; color:#010304;">; +234 803 223 4502</span></p>
    <p><span style="font-family:'SpaceGrotesk';">&nbsp;</span></p>
    <p style="bottom: 10px; right: 10px; position: absolute;"><a href="https://wordtohtml.net" target="_blank" style="font-size:11px; color: #d0d0d0;">Converted to HTML with WordToHTML.net</a></p>
</body>

</html>
           """,
            onTapUrl: (url) async {
              if (await canLaunchUrl(Uri.parse(url))) {
              await launchUrl(
              Uri.parse(url),
              );
              } else {
              throw 'Could not launch $url';
              }
              return true;
            },

              ),
        ),
      ),

    );
  }
}
